.TH RADAR 1 2005\-07\-28 Development 
.SH NAME
radar \- rapid application discovery and retrieval
.SH SYNOPSIS
\fBradar\fR
.SH DESCRIPTION
radar is a system for indexing free and
open source codebases from the web into a comprehensive software
ontology. It uses free tools for spidering and scraping, focused
crawling, information extraction, text classification, and
ontological engineering to accomplish this. As these systems are
identified and interrelated, a more coherent system results.
.PP
\fBradar.el\fR) is the GNU Emacs minor mode for
RADAR. It allows the user to guide the focused crawling process
through w3m\-el and also navigate the
comprehensive software ontology .
.PP
Additionally, using Debaux , you
can automatically generate Debian GNU/Linux packages for Perl Modules.

.nf
sudo radar install WWW::Search::CraigsList
.fi

.PP
You can index a website with 

.nf
radar
    http://www.myurl.org  
.fi

\&. Radar will prompt you
approve its classification and then index the system.
.SH FILES
\fB/usr/share/radar/radar.el\fR.
.SH AUTHOR
These programmes are made by A. Dougherty
<andrewdo@andrew.cmu.edu>, as well as this
documentation.
.SH THANKS
Radar uses functionality from many different programs.
Thanks to the authors of these programs.
.SH COPYRIGHT
Copyright 2005 A. Dougherty and released under the
GNU General Public License
(GPL). Permission is granted to copy,
distribute and/or modify this document under the terms of the
GNU Free Documentation License, Version 1.1;
with no Invariant Sections, no Front\-Cover Texts and no
Back\-Cover Texts.
.SH BUGS
.SH HISTORY
